repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: name-tests-test
        files: ^tests/.+\.py$
    -   id: fix-encoding-pragma
    -   id: flake8
        exclude: ^docs
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v1.3.5
    hooks:
    -   id: reorder-python-imports
        args: [
            '--add-import', 'from __future__ import absolute_import',
            '--add-import', 'from __future__ import unicode_literals',
        ]
        files: ^(pyramid_mock_server/|tests/).*\.py$
        language_version: python2.7
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
        args:
        - -i
        - --ignore=E265,E309
        - --max-line-length=100
