language: python

matrix:
  include:
  - env: TOXENV=py27
  - env: TOXENV=py35
    python: "3.5"
  - env: TOXENV=py36
    python: "3.6"

  - env: TOXENV=docs
  - env: TOXENV=pre-commit

install:
- "pip install tox coveralls"
script:
- tox
after_success:
- coveralls
# Faster runs on container based infrastucture
sudo: false
